services:
  password-cracker-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - password-cracker-network
    ports:
      - "5173:5173"
    restart: always

  password-cracker-backend-central:
    build:
      context: "./backend - central"
      dockerfile: Dockerfile
    volumes:
      - "./backend - central:/App"
    env_file:
      - .env
    ports:
      - "5098:5098"
    depends_on:
      - password-cracker-database
    networks:
      - password-cracker-network

  password-cracker-database:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - password-cracker-network
    ports:
      - "5432:5432"

networks:
  password-cracker-network:
    driver: bridge

volumes:
  db_data:
