services:
  password-cracker-backend-calculating:
    build:
      context: "./backend - calculating"
      dockerfile: Dockerfile
    volumes:
      - "./backend - calculating:/Calculating"
      - ".env:/Calculating/.env"
      - "./data:/Calculating/data"
    ports:
      - "5099:5099"
    env_file:
      - .env
    environment:
      - PASSWORD_FILE_PATH=/Calculating/data/users_passwords.txt
    networks:
      - password-cracker-network

networks:
  password-cracker-network:
    driver: bridge