services:
  password-cracker-backend-calculating:
    build:
      context: "./backend - calculating"
      dockerfile: Dockerfile
    volumes:
      - "./backend - calculating:/App"
      - ./dictionary:/dictionary
    ports:
      - "5099:5099"
    env_file:
      - .env
    networks:
      - password-cracker-network

networks:
  password-cracker-network:
    driver: bridge
