services:
  password-cracker-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - password-cracker-network
    ports:
      - "5173:5173"
    restart: always

  password-cracker-backend-central:
    build:
      context: "./backend - central"
      dockerfile: Dockerfile
    volumes:
      - "./backend - central:/Central"
      - ".env:/Central/.env"
      - "./data:/Central/data"
    env_file:
      - .env
    environment:
      - PASSWORD_FILE_PATH=/Central/data/users_passwords.txt
      - DOTNET_USE_POLLING_FILE_WATCHER=false
      - DOTNET_WATCH_SUPPRESS_MSBUILD_INITIATION=true
    ports:
      - "5098:5098"
    networks:
      - password-cracker-network

networks:
  password-cracker-network:
    driver: bridge

volumes:
  db_data: